apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- application-config-cm.yaml
- deployment.yaml
- ingress.yaml
- service.yaml
- nginx-html-folder-cm.yaml
