apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

configMapGenerator:
- name: application-config-cm
  envs:
  - application-config.properties
generatorOptions:
  disableNameSuffixHash: true

resources:
- deployment.yaml
- ingress.yaml
- service.yaml
- nginx-html-folder-cm.yaml
